### ISSUE TITLE
small tutorial

### ISSUE THREAD

**Issue by Bomberchibbi** [denesik/hustle_castle_bot_pack#1]
Hello,

I tried geting this to run in jupyter, without any success though. Could you please tell me how to do it? I read your readme but when I start observe it just immedietly shuts down again.

best regards

**Comment by denesik** [comment]
First you need NoxPlayer_log.txt
But since the computer is very specific, it may not be possible to get the bot to work.
For a quick connection and to extend the trial period, write me a discord:
https://discord.gg/x6rXGjZ

Для начала нужен NoxPlayer_log.txt
Но так как компьютер весьма специфичный, возможно не получиться заставить работать бот.
Для быстрой связи и для продления trial периода напишите мне в дискорд:
https://discord.gg/x6rXGjZ
